export * from './types';
export * from './engine';
export { fetchFigmaScreen, listFigmaScreens } from './adapters/design/figma';
export { fetchZeplinScreen, listZeplinScreens } from './adapters/design/zeplin';
export { captureScreen, captureWeb, captureAndroid, captureIOS } from './adapters/capture/screenshot';
export { runPixelDiff, extractMismatchRegions } from './analysis/pixeldiff';
export { runAIAnalysis } from './analysis/aianalysis';
export { annotateScreenshot, createComparisonImage } from './analysis/annotator';
export { computeAccuracyScore, getStatus } from './analysis/scorer';
export { generateHTMLReport } from './report/htmlreport';
